### ISSUE TITLE
Select a focus area & Set Q1 goals

### ISSUE THREAD

**Issue by dkhowala** [openstax/ux#57]
### Description
Take on a focus area in addition to your product team, and a secondary area you will help with: 
Each designer choose an area to specialize in and a secondary area to learn more about from the following:
- Accessibility
- Adopter advisory boards 
- Brand Book and Pattern Library
- Usability Evaluation

https://docs.google.com/document/d/10afMBoF-ONeB049PP7uUDNkYViqlsbRdExbX0DSFSI8/edit

### Acceptance Criteria
- [x] Meet with Kathi to set Devika's focus area
- [x] Set Devika's Q1 goals
- [x] Meet with Kathi to set Suhani's focus area
- [x] Set Suhani's Q1 goals
- [x] Meet with Kathi to set Victoria's focus area
- [x] Set Victoria's Q1 goals

**Comment by victoria-cooke** [comment]
@allisonhowell @meeragovindaraju
