### ISSUE TITLE
Organize UX Tools

### ISSUE THREAD

**Issue by victoria-cooke** [openstax/ux#58]
### Description
Organize Sketch, Axure, InVision, and Abstract tools so that they are easy to access/maintain.
Current License Info: Axure (3)  and Sketch (8-10) Invision (1 master + 2 contributors).

https://docs.google.com/spreadsheets/d/1rft1uNI2BhEX5qjoS7PsE3Q1zsafYSYRXI-GfgnlGbo/edit#gid=2077360193

### Acceptance Criteria
Complete checklists.

**Main Tasks**

- [x] Centralize all software licensing information
- [x] Write orientation documentation for each program
- [x] Make designs centrally accessible

**Pending Subtasks**

- [x] Locate or obtain Axure licenses (@victoria-cooke ) 
- [x] Obtain upgraded InVision administrator account (@victoria-cooke ) 
- [x] Establish criteria for onboarding info (@snm8 )
- [x] Establish preferred access point(s) for designs and determine who needs access- Devika
- [x] Obtain Balsamiq licenses (@snm8 )

**Comment by victoria-cooke** [comment]
@allisonhowell @meeragovindaraju

**Comment by snm8** [comment]
Completed documentation for balsamiq. Uploaded in drive: https://drive.google.com/open?id=10ywtmKaoYMgtZwRB69KMsnpZ6aojc4mF3R9y0hZ5g40
Also updated software spreadsheet

**Comment by victoria-cooke** [comment]
@snm8 Thanks! I'll add the InVision, Axure, Adobe CC, Microsoft Office, Sketch, and Abstract pieces to this document as well. We should be able to check it off after that.
