### ISSUE TITLE
Determine Q1 product team needs

### ISSUE THREAD

**Issue by snm8** [openstax/ux#61]
### Description
Determine the designs, research, and usability evaluation needs for each of the product teams for Q1

### Acceptance Criteria
- [x] UX person meets with product manager
- [x] Get all work on product board
- [x] Get all work on UX board
- [x] Incorporate the needs into UX person's 3 month goals

### **Q1 Focus Areas & Goals:**
**Victoria**
Focus: Brand Book and Pattern Library
Goal: Research and document current OS branding
**Devika**
Focus: Accessibility
Goal: Document the basic (AA compliant) accessibility standards for UX design at OpenStax for others to follow.

**Comment by kathi-fletcher** [comment]
Designers need to make sure that the Q1 design gets onto the product boards and then link over here.
