### ISSUE TITLE
Write process for UX Work Management document

### ISSUE THREAD

**Issue by victoria-cooke** [openstax/ux#75]
### Description
Detail the specifics of how UX will manage work, files, etc.
https://docs.google.com/document/d/1ddwjhP9rg667ezrUQ-wHXzP0bDlne0H60cYlFre2PGQ/edit#heading=h.1wbq2z3asln5

### Acceptance Criteria
- [ ] Have UX Manager sign off on final document

**Comment by BruceP99166** [comment]
Blocked awaiting arrival of UX Manager.
