### ISSUE TITLE
Document the accessibility compliance of existing OpenStax UI elements and make recommendation for improvement.

### ISSUE THREAD

**Issue by BruceP99166** [openstax/ux#77]
# Description
At OpenStax, ensuring that our content is accessible for a wide range of users is of great importance. As a product team member, I want to know if all the user-facing UI elements of my product meet accessibility standards (AA) set by WCAG and what can be done to improve them.

# Acceptance Criteria
- Check and document at least 20 UI elements from the current OS pattern library against WCAG AA compliance. 
- Make recommendations for elements that require improvement.

**Comment by dkhowala** [comment]
Work In progress doc: https://docs.google.com/spreadsheets/d/1s3tchSxSPluogO2mHG1MbMdagUMI9MACyyEYYu9TuY8/edit#gid=180293927
